"""Estrutura inicial do banco de dados

Revision ID: aee592ba7530
Revises: 
Create Date: 2025-05-04 13:53:38.063637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee592ba7530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('snmp_community', sa.String(length=64), nullable=True),
    sa.Column('snmp_version', sa.String(length=8), nullable=True),
    sa.Column('snmp_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    with op.batch_alter_table('olt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_olt_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('onu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onu_serial_number'), ['serial_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onu_serial_number'))

    op.drop_table('onu')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('olt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_olt_name'))

    op.drop_table('olt')
    op.drop_table('log_entry')
    # ### end Alembic commands ###
